apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.application.name }}
  labels:
    name: svc-{{ .Values.application.name }}
    component: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: http
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.target.port }}
  type: LoadBalancer
